modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/mrbysco/candyworld/issues"
license="MIT"

[[mods]]
modId="candyworld"
version="${file.jarVersion}"
displayName="Candy World - ReCaramelized"
displayURL="https://www.curseforge.com/minecraft/mc-mods/candy-world-recaramelized"
authors="Mrbysco, ochotonida"
description='''
Adds some new tasty biomes
'''
[[dependencies.candyworld]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"